### ISSUE TITLE
Infinite loop in redrawing crashes apps

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#574]
There's a bug introduced in 74b66d2 that crashes any real app with a TextBlocks. Test with this minimal example:

``` ruby
Shoes.app do
  para "Infinite."
end
```

Apps fail for me with one of two errors (sorry, it's late). One is a "Stack level too deep". The one I'm getting now is more entertaining...a `NoMethodError` on an instance of `NoMethodError`:

```
NoMethodError: undefined method `join' for #<NoMethodError:0x39e2cdaa>
   _after_do_execute_callback at /Users/eric/.rvm/gems/jruby-1.7.8@shoes/gems/after_do-0.2.2/lib/after_do.rb:122
  _after_do_execute_callbacks at /Users/eric/.rvm/gems/jruby-1.7.8@shoes/gems/after_do-0.2.2/lib/after_do.rb:108
                         each at org/jruby/RubyArray.java:1613
  _after_do_execute_callbacks at /Users/eric/.rvm/gems/jruby-1.7.8@shoes/gems/after_do-0.2.2/lib/after_do.rb:107
                         each at org/jruby/RubyArray.java:1613
  _after_do_execute_callbacks at /Users/eric/.rvm/gems/jruby-1.7.8@shoes/gems/after_do-0.2.2/lib/after_do.rb:106
                execute_block at /Users/eric/.rvm/gems/jruby-1.7.8@shoes/gems/after_do-0.2.2/lib/after_do.rb:90
       create_execution_block at /Users/eric/code/shoes4/lib/shoes/app.rb:224
                         call at org/jruby/RubyProc.java:271
                   eval_block at /Users/eric/code/shoes4/lib/shoes/slot.rb:46
                       append at /Users/eric/code/shoes4/lib/shoes/slot.rb:55
                   eval_block at /Users/eric/code/shoes4/lib/shoes/app.rb:218
                    setup_gui at /Users/eric/code/shoes4/lib/shoes/app.rb:102
                   initialize at /Users/eric/code/shoes4/lib/shoes/app.rb:31
                          app at /Users/eric/code/shoes4/lib/shoes/app.rb:15
                       (root) at /Users/eric/tmp/tall_slot.rb:1
                         load at org/jruby/RubyKernel.java:1103
                       (root) at /Users/eric/code/shoes4/lib/shoes/cli.rb:1
                  execute_app at /Users/eric/code/shoes4/lib/shoes/cli.rb:73
                       (root) at bin/ruby-shoes:6
```

The root of the problem is [this line](https://github.com/shoes/shoes4/commit/74b66d2436b3c5980d147cd1e07425054169c0ff#diff-7e0f0c65bed54edece5dcb66b949dc6eR20). After this addition, on redraw, we get a series of calls like this:

```
Shoes::Swt::RedrawingAspect#update_gui ->
Shoes::Swt::App#flush ->
Shoes::Swt::ShoesLayout#layout
Shoes::Slot#contents_alignment ->
Shoes::Slot#position_contents ->
Shoes::Slot#positioning ->
Shoes::Slot#position_element ->
Shoes::TextBlock#_position (from Shoes::Common::CommonMethods) ->
Shoes::Swt::TextBlock#update_position ->
Shoes::Swt::RedrawingAspect#update_gui (and back around again)
```

One problem is that we don't have a spec that covers this, so all of the specs pass even though practically no app could run.

As far as a fix, simply removing the offending line seems to work for this simple case, but it causes a couple of specs to fail. @PragTob, can we just remove this line, or will it cause other problems?
