### ISSUE TITLE
Undefined local variable or method 'java' for Shoes::Sound:Class

### ISSUE THREAD

**Issue by jrgifford** [shoes/shoes4#39]
I've tested in Ubuntu 12.04 32 and 64 bit, as well as Fedora 17 32.

When I run any of the examples, I get the following error:

> NameError: undefined local variable or method `java' for Shoes::Sound:Class
>    Sound at /home/jrg/code/shoes4/lib/shoes/sound.rb:19
>    Shoes at /home/jrg/code/shoes4/lib/shoes/sound.rb:16
>   (root) at /home/jrg/code/shoes4/lib/shoes/sound.rb:15
>  require at org/jruby/RubyKernel.java:1042
>  require at /home/jrg/.rvm/rubies/jruby-1.6.7.2/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36
>  (root) at /home/jrg/code/shoes4/lib/shoes/sound.rb:28

it appears that this was introduced in dcec852c33cf23ea847de0550eeab0383c60f628.

I haven't had a chance to test on Windows yet. Thoughts on what might be causing this?
